import type { Metadata } from "next";
import localFont from "next/font/local";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import HolyLoader from "holy-loader";

import { ThemeProvider } from "@/lib/providers/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import { GridBg } from "@/components/composite/images";
import { ScrollTop } from "@/components/composite/scroll";
import { SiteFooter, SiteHeader } from "@/components/composite/site";
import { TailwindIndicator } from "@/components/composite/tailwind";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HolyLoader color="#ccc" />
        <ThemeProvider attribute="class" defaultTheme="dark">
          <div className="relative flex min-h-screen flex-col bg-background" vaul-drawer-wrapper="">
            <GridBg />
            <SiteHeader />
            <div className="relative flex-1 py-4">{children}</div>
            <SiteFooter />
          </div>
          <TailwindIndicator />
          <ScrollTop />
        </ThemeProvider>
        <Analytics />
        <Toaster />
        <SpeedInsights />
      </body>
    </html>
  );
}
